/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express=require("express")
const app=express()
todosDatabase=[{
  title:"Exercise",
  description:"Go to Gym",
  completed:false,
  id:1
},{
  title:"Breakfast",
  description:"Eat Oats",
  completed:false,
  id:2
}]
app.use(express.json()); //imp -To fix this issue, you need to add a middleware to parse the request body as JSON. You can use the express.json() middleware to achieve this.


//  1.GET /todos - Retrieve all todo items
app.get("/todos",(req,res)=>{
  res.json(todosDatabase)
})

//2. GET /todos/:id - Retrieve a specific todo item by ID
app.get("/todos/:id",(req,res)=>{
  const specificID=req.params.id
  let SpecificIDtodoPresent=false
  for(let i=0;i<todosDatabase.length;i++){
    if(todosDatabase[i].id==specificID){
      SpecificIDtodoPresent=true
      SpecificIDtodo=todosDatabase[i]
    }
  }
  if(SpecificIDtodoPresent){
    res.json(SpecificIDtodo)
  }else{
    res.status(404).send('Todo cannot be found')
  }

  
})

//3. POST /todos - Create a new todo item
app.post("/todos",(req,res)=>{
  const title=req.body.title
  const completed=req.body.completed
  const description=req.body.description
  let idOfAddedTodo=1;
  for(let i=0;i<todosDatabase.length;i++){
    idOfAddedTodo+=1;
  }
  
  todosDatabase.push({
    title,
    completed,
    description,
    id:idOfAddedTodo
  })
  res.status(200+idOfAddedTodo).json(todosDatabase)

})

// 4. PUT /todos/:id - Update an existing todo item by ID
app.put("/todos/:id",(req,res)=>{
  const CompletedTaskID=req.params.id
  let GetSpecificIDtodoPresent=false
  let CompletedTodo=[]
  for(let i=0;i<todosDatabase.length;i++){
    if(todosDatabase[i].id==CompletedTaskID){
      GetSpecificIDtodoPresent=true
      todosDatabase[i].completed=true
      CompletedTodo=todosDatabase[i]
    }
  }
  if(GetSpecificIDtodoPresent){
    res.json(CompletedTodo)
  }else{
    res.status(404).send('Todo cannot be found, incorrect ID provided')
  }

})

//5. DELETE /todos/:id - Delete a todo item by ID
app.delete("/todos/:id",(req,res)=>{
  const TodoDeleteTaskID=req.params.id
  let DeletedIDpresent=false
  
  for(let i=0;i<todosDatabase.length;i++){
    if(todosDatabase[i].id==TodoDeleteTaskID){
      DeletedIDpresent=true
      todosDatabase.splice(i,1) // remove 1 element at index 2
    }
  }
  if(DeletedIDpresent){
    res.json(todosDatabase)
  }else{
    res.status(404).send('Todo cannot be deleted, incorrect ID provided')
  }

})

app.listen(3006)