import type { Metadata } from "next";
import { Geist, Geist_Mono, Mukta } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const mukta = Mukta({
  subsets: ['latin'], // You can include other subsets like 'devanagari' if needed
  weight: ['400', '500', '600', '700'], // Choose font weights you need
  variable: '--font-mukta', // CSS variable for easy access
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mukta.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
